[project]
name = "skinlesionclassification"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.12"
dependencies = [
    "opencv-python>=4.13.0.92",
    "plotly>=6.5.2",
    "scikit-learn>=1.8.0",
    "streamlit>=1.54.0",
    "tensorflow[and-cuda]>=2.16.0", # important for 4060 Ti
    "vit-keras>=0.2.0",
]
